RunawayNext/RunawayNext/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
<<<<<<< HEAD
    path('profiles/', include('django.contrib.auth.urls')),
    path('', include('profiles.urls')),
=======
     path('registration/', include('django.contrib.auth.urls')),
>>>>>>> a234bd7e1f4c6e8b44d5edfa225b37e924ed0d06
    path('', include('runaway.urls'))
]

RunawayNext/profiles/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='profiles'

urlpatterns=[
    path('profiles/signup/', views.CreateLogInView.as_view(), name='sign_up'),
    path('<str:username>/edit/', views.EditUserProfileView.as_view(), name='edit_profile'),
    path('profiles/<str:username>/', views.UsernameProfileView.as_view(), name='post_list'),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RunawayNext/runaway/urls.py
from django.urls import path

from . import views

app_name='runaway'

urlpatterns=[
    path('', views.PostListView.as_view(), name="home"),
<<<<<<< HEAD
    path('profiles/post/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('profiles/post/create/', views.PostCreateView.as_view(), name='create'),
    path('post/<int:pk>/update', views.PostUpdateView.as_view(), name='update'),
    path('post/<int:pk>/delete', views.PostDeleteView.as_view(), name='delete'),
=======
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('register/', views.CreateLogInView.as_view(), name='register'),
    path('post/new/', views.PostCreateView.as_view(), name='create'),
    path('post/<int:pk>/update', views.PostUpdateView.as_view(), name='update'),
    path('post/<int:pk>/delete', views.PostDeleteView.as_view(), name='delete'),
    path('<str:username>/', views.PostList.as_view(), name='post_list'),
>>>>>>> a234bd7e1f4c6e8b44d5edfa225b37e924ed0d06
] 

RunawayNext/profiles/models.py
from django.db import models

# Create your models here.

RunawayNext/runaway/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import timedelta
from django.db.models.signals import post_save
from django.dispatch import receiver

class Post(models.Model):
<<<<<<< HEAD
    post=models.TextField()
    description=models.CharField(max_length=300)
    username=models.ForeignKey('auth.User', on_delete=models.CASCADE)
    posted=models.DateTimeField(auto_now_add=True)
    edited=models.DateTimeField(auto_now=True)
    location=models.CharField(max_length=150)
    lat=models.FloatField()
    lng=models.FloatField()
    
=======
    post=models.TextField(max_length=1000, blank=True)
    username=models.ForeignKey('auth.User', on_delete=models.CASCADE)
    posted=models.DateTimeField(auto_now_add=True)
    edited=models.DateTimeField(auto_now=True)
    location=models.CharField(max_length=50, blank=True)
>>>>>>> a234bd7e1f4c6e8b44d5edfa225b37e924ed0d06

    def __str__(self):
        return self.post

    def get_absolute_url(self):
        return reverse('posts:detail', args=[str(self.id)])

    @property
    def time_diff(self):
        return (self.edited - self.posted)>timedelta(seconds=1)

class UserProfile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
<<<<<<< HEAD
    name=models.CharField(max_length=50, blank=True)
    bio=models.TextField(max_length=150, blank=True)
    residence=models.CharField(max_length=100, blank=True)
    image=models.ImageField(upload_to='user_profiles', blank=True)
=======
    bio=models.TextField(max_length=150, blank=True)
    residence=models.CharField(max_length=50, blank=True)
>>>>>>> a234bd7e1f4c6e8b44d5edfa225b37e924ed0d06
    
    def __str__(self):
        return self.user.username
    
def create_profile(sender, **kwargs):
<<<<<<< HEAD
    user=kwargs["instance"]
    if kwargs['created']:
        user_profile=UserProfile(user=user)
        user_profile.save()

post_save.connect(create_profile, sender=User)

=======
    if kwargs['created']:
        user_profile=UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)
>>>>>>> a234bd7e1f4c6e8b44d5edfa225b37e924ed0d06
  

  

RunawayNext/profiles/forms.py
from django import forms
from runaway.models import UserProfile
 
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('image','name', 'bio', 'residence') 

    def save(self, user=None):
        user_profile = super(UserProfileForm, self).save(commit=False)
        if user:
            user_profile.user = user
        user_profile.save()
        return user_profile

RunawayNext/profiles/views.py
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.contrib.auth.models import User
from django.core import serializers

from runaway.models import Post, UserProfile
from profiles.forms import UserProfileForm


class CreateLogInView(generic.CreateView):
    form_class=UserCreationForm
    success_url=reverse_lazy('login')
    template_name='signup.html'

class UsernameProfileView(generic.DetailView):
    model=User
    template_name='user_profiles.html'  
    context_object_name='user_profile'
    
    def get_object(self):
        return get_object_or_404(User, username=self.kwargs.get('username'))

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['point_list']=serializers.serialize('json', self.object.post_set.all())
        return context
       
class ProfileView(FormView):
    template_name='user_profiles.html'
    form_class=UserProfileForm

    
    def form_valid(self, form):
        form.save(self.request.user)
        return super(ProfileView, self).form_valid(form)

    def get_success_url(self, *args, **kwargs):
        return reverse('runaway:home')
    
 
class EditUserProfileView(UpdateView): 
    model = UserProfile
    form_class = UserProfileForm
    template_name = 'edit_profile.html'

    def get_object(self):
        user= get_object_or_404(User, username=self.kwargs.get('username'))
        return user.userprofile

    def get_success_url(self, *args, **kwargs):
        return reverse('runaway:home')

RunawayNext/runaway/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView 
from django.urls import reverse_lazy
from django.shortcuts import render
from django. contrib.auth.forms import UserCreationForm
<<<<<<< HEAD
from django.contrib.auth.decorators import login_required
=======
from django.views import generic
>>>>>>> a234bd7e1f4c6e8b44d5edfa225b37e924ed0d06

from .models import Post, UserProfile


class PostListView(ListView):
    model = Post
    template_name = 'home.html'

    def get_queryset(self):
        return Post.objects.all().order_by('-posted')

class PostDetailView(DetailView):
    model=Post
<<<<<<< HEAD
    template_name='popup_view.html' 
=======
    template_name='user_profiles.html'
    
class PostCreateView(CreateView):
    model=Post
    template_name='get_create.html'
    fields=['username','location', 'post']
    success_url=reverse_lazy('runaway:home')

    def if_valid(self, form):
        form.instance.username=self.request.username
        return super().if_valid
>>>>>>> a234bd7e1f4c6e8b44d5edfa225b37e924ed0d06

class PostUpdateView(UpdateView):
    model=Post
    template_name='get_update.html'
<<<<<<< HEAD
    fields=['description','post']
=======
    fields=['post']
>>>>>>> a234bd7e1f4c6e8b44d5edfa225b37e924ed0d06
    success_url=reverse_lazy('runaway:home')
 

class PostDeleteView(DeleteView):
    model=Post
    template_name='get_delete.html'
    success_url=reverse_lazy('runaway:home')

<<<<<<< HEAD

class PostCreateView(CreateView):
    model=Post
    template_name='get_create.html'
    fields=['location', 'lng', 'lat', 'description', 'post']
    success_url=reverse_lazy('runaway:home')
    
    def form_valid(self, form):
        form.instance.username=self.request.user
        form.save()
        return super().form_valid(form)

=======
class CreateLogInView(generic.CreateView):
    form_class=UserCreationForm
    success_url=reverse_lazy('login')
    template_name='register.html'

class UsernameListView(generic.DetailView):
    model=UserProfile
    template_name='user_profiles.html'

class PostList(generic.ListView):
    model=Post
    template_name='user_profiles.html'  
>>>>>>> a234bd7e1f4c6e8b44d5edfa225b37e924ed0d06

RunawayNext/runaway/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
 <head>
    <meta charset='utf-8' />
    <title>RunawayNext</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.0.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.0.0/mapbox-gl.css' rel='stylesheet' />
    <script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.3.0/mapbox-gl-geocoder.min.js'></script>
    <link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.3.0/mapbox-gl-geocoder.css' type='text/css' />
<<<<<<< HEAD
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script&display=swap" rel="stylesheet">
 </head>
  <body>
    <header>
      <div id="right">
       {% if user.is_authenticated %}
        <a href="{% url 'runaway:home' %}"><i class="fas fa-home"></i></a>
        <a href="{% url 'profiles:post_list' user.username %}"><i class="fas fa-map-marked-alt"></i></a>
        <a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i></a>
       {% else %}
        <a href="{% url 'login' %}">Log In</a>
        <a href="{% url 'profiles:sign_up' %}">Sign Up</a>
       {% endif %}
     </div>
     <div>
        <h1><a href="{% url 'runaway:home' %}">RunawayNext</a></h1>
      </div>
=======
  </head>
  <body>
    <header>
      <h1><a href="{% url 'runaway:home' %}">RunawayNext</a></h1>
      <div>
       {% if user.is_authenticated %}
         <div id="right">
         <p><a href="{% url 'logout' %}">Logout</a></p>
         </div>
       {% else %}
         <div id="right">
         <a href="{% url 'login' %}">Log In</a><a href="{% url 'runaway:register' %}">Sign Up</a>
         </div>
       {% endif %}
     </div>
>>>>>>> a234bd7e1f4c6e8b44d5edfa225b37e924ed0d06
    </header>
      <div>
      {% block content %}
      {% endblock content %}
<<<<<<< HEAD
      </div>
      <footer>
      <p>I'll put something here later.</p>
=======

>>>>>>> a234bd7e1f4c6e8b44d5edfa225b37e924ed0d06
    <script src="{% static 'JavaScript/maps.js' %}"></script>
  </body> 
</html>

RunawayNext/runaway/templates/edit_profile.html
{% extends 'base.html' %}

{% block content %}
  <h2>Edit Profile</h2>                            >
  <form action="" method='post' enctype="multipart/form-data">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Post">
  </form>
{% endblock content %}

RunawayNext/runaway/templates/get_create.html
{% extends 'base.html' %}

{% block content %}
<<<<<<< HEAD
  <h2>New Post</h2>
=======
  <h1>New Post</h1>
>>>>>>> a234bd7e1f4c6e8b44d5edfa225b37e924ed0d06
  <form action="" method='post'>
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Post">
  </form>
{% endblock content %}

RunawayNext/runaway/templates/get_delete.html
{% extends 'base.html' %}


{% block content %}
<<<<<<< HEAD
  <h2>Delete</h2>
=======
  <h1>Delete</h1>
>>>>>>> a234bd7e1f4c6e8b44d5edfa225b37e924ed0d06
  <form action='' method='post'>
  {% csrf_token %}
  <p> Are you sure you want to delete? This can't be undone.</p>
  <input type="submit" value="Delete">
  </form>
{% endblock content %}

RunawayNext/runaway/templates/get_update.html
{% extends 'base.html' %}


{% block content %}
<<<<<<< HEAD
  <h2>Edit Post</h2>
=======
  <h1>Edit Post</h1>
>>>>>>> a234bd7e1f4c6e8b44d5edfa225b37e924ed0d06
  <form action='' method='post'>
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Edit">
  </form>
{% endblock content %}

RunawayNext/runaway/templates/home.html
{% extends 'base.html' %}

{% block content %}
<<<<<<< HEAD
  {% if user.is_authenticated %}
    {% comment %} <div  class="banner">
      <h2><a href="{% url 'profiles:post_list' user.username %}">{{ user.username }}</a></h2>
    </div> {% endcomment %}
  {% endif %}
  {% for post in object_list %}
  <div class="posts">
      <h4>{{post.location}}</h4>
      {% if post.username.userprofile.image %}
      <img src="{{ post.username.userprofile.image.url }}"></a>
      {% endif %}
      <h3><a href="{% url 'profiles:post_list' post.username %}">@{{ post.username }}</a><h3>
      
      <h5><em>Posted on {{ post.posted }}</em><h5>
      {% if post.time_diff %}
        <h5><em>Post updated on {{post.edited}}</em><h5>
      {% endif %}
      <div id="description">
        <p>{{post.description}}</p> 
        <a href="{% url 'runaway:detail' post.pk %}">READ MORE</a>
      </div>
  </div>
=======
      {% if user.is_authenticated %}
        <div  class="banner">
        <p id="right"><a href="{% url 'runaway:post_list' user.username %}">Add Location</a></p>
        <h1><a href="{% url 'runaway:post_list' user.username %}">{{ user.username }}</a></h1>
        </div>
  {% endif %}
  {% for post in object_list %}
  <div class="posts">
  <div>
    <h3><a href="{% url 'runaway:post_list' post.username %}">@{{ post.username }}</a><h3>
    <h4>{{post.location}}</h4>
    <p>{{post.post}}</p> 
    <h5><em>Posted on {{ post.posted }}</em><h5>
    {% if post.time_diff %}
      <h5><em>Post updated on {{post.edited}}</em><h5>
    {% endif %}
  </div>
  <div>
    {% if user == post.username %}
    {% if user.is_authenticated %}
      <a href="{% url 'runaway:update' post.pk %}">Edit</a>
      <a href="{% url 'runaway:delete' post.pk %}">Delete</a> 
     {% endif %}
    {% endif %} 
     </div>
    </div>
>>>>>>> a234bd7e1f4c6e8b44d5edfa225b37e924ed0d06
  {% endfor %}
{% endblock content %}

RunawayNext/runaway/templates/popup_view.html
{% extends 'base.html' %}

{% block content %}
  <div>
    <div class="crop">
    {% if post.username.userprofile.image %}
    <img src="{{ post.username.userprofile.image.url }}">
    {% endif %}
    </div>
    <h2>{{ post.location }}</h2>
    <h4><em>Posted at {{ post.posted }} by {{ post.username }}</em></h4>
    {% if post.created_updated_differ %}
      <h4><em>Post last updated at {{ post.edited }}</em></h4>
    {% endif %}
    <p id="detail">{{ post.post }}</p>
  </div>
  <div id="right">
  {% if user == post.username %}
  {% if user.is_authenticated %}
    <p><a href="{% url 'runaway:update' post.pk %}">+ Edit Blog Post</a></p>
    <p><a href="{% url 'runaway:delete' post.pk %}">+ Delete Blog Post</a></p>
  </div>
    
  {% endif %}
  {% endif %}
{% endblock content %}

RunawayNext/runaway/templates/register.html
{% extends "base.html" %}
{% block content %}
  <div>
    <form method='POST' action="">
    {% csrf_token %}
        <p>{{ form }}</p>
        <button type="submit">Sign Up</button>
    </form>
  </div>
{% endblock content %}

RunawayNext/runaway/templates/signup.html
{% extends "base.html" %}
{% block content %}
  <div>
    <form method='POST' action="">
    {% csrf_token %}
        <p>{{ form }}</p>
        <button type="submit">Sign Up</button>
    </form>
  </div>
{% endblock content %}

RunawayNext/runaway/templates/user_profiles.html
  {% extends 'base.html' %}
    {% block content %}
<<<<<<< HEAD
    {% csrf_token %}
    <div class="profile">
    <div class="crop">
    {% if user_profile.userprofile.image %}
    <img src="{{ user_profile.userprofile.image.url }}">
    {% endif %}
    </div>
    <h2>{{ user_profile.userprofile.user }}</h2>
    <p>{{ user_profile.userprofile.name }}<p>
    <p>{{ user_profile.userprofile.bio }}</p>
    <p>{{ user_profile.userprofile.residence }}</p>
    {% if user == user_profile.userprofile.user %}
    {% if user.is_authenticated %}
    <div id="right">
      <button type="submit"><a href="{% url 'profiles:edit_profile' user_profile.username %}">Edit Profile</a></button>
      <button type="submit" id="submit">Add Marker</button>
    </div>
    {% endif %}
    {% endif %}
    <div id='map'>
    </div>
    </div>
    {{point_list|json_script:"loc-data" }}
=======
    <h1>{{ user.username }}</h1>
    <p>bio:{{ user.bio }}</p>
    <p>location:{{ user.location }}</p>
    {% if user.is_authenticated %}
    <div>
      <button type="submit" id="submit">Add Marker</button>
    </div>
    {% endif %}
    <div id='map'></div>
>>>>>>> a234bd7e1f4c6e8b44d5edfa225b37e924ed0d06
    {% endblock content %}
  